public class Main {
    public static void main(String[] args) {
        System.out.println("Создать EmployeeBook");
        EmployeeBook employeeBook = new EmployeeBook();
        System.out.println("-------------------");
        System.out.println("Добавить Employee 1");
        System.out.println(employeeBook.addEmployee(new Employee("Name1", "Surname1", "SecondName1", 1, 20000)));
        System.out.println("-------------------");
        System.out.println("Добавить Employee 2");
        System.out.println(employeeBook.addEmployee(new Employee("Name2", "Surname2", "SecondName2", 1, 20000)));
        System.out.println("-------------------");
        System.out.println("Добавить Employee 3");
        System.out.println(employeeBook.addEmployee(new Employee("Name3", "Surname3", "SecondName3", 2, 21000)));
        System.out.println("-------------------");
        System.out.println("Добавить Employee 4");
        System.out.println(employeeBook.addEmployee(new Employee("Name4", "Surname4", "SecondName4", 2, 20000)));
        System.out.println("-------------------");
        System.out.println("Добавить Employee 5");
        System.out.println(employeeBook.addEmployee(new Employee("Name5", "Surname5", "SecondName5", 3, 19000)));
        System.out.println("-------------------");
        System.out.println("Добавить Employee 6");
        System.out.println(employeeBook.addEmployee(new Employee("Name6", "Surname6", "SecondName6", 3, 22000)));
        System.out.println("-------------------");
        System.out.println("Добавить Employee 7");
        System.out.println(employeeBook.addEmployee(new Employee("Name7", "Surname7", "SecondName7", 4, 28000.5)));
        System.out.println("-------------------");
        System.out.println("Добавить Employee 8");
        System.out.println(employeeBook.addEmployee(new Employee("Name8", "Surname8", "SecondName8", 4, 16500)));
        System.out.println("-------------------");
        System.out.println("Добавить Employee 9");
        System.out.println(employeeBook.addEmployee(new Employee("Name9", "Surname9", "SecondName9", 5, 25300)));
        System.out.println("-------------------");
        System.out.println("Добавить Employee 10");
        System.out.println(employeeBook.addEmployee(new Employee("Name10", "Surname10", "SecondName10", 5, 16000)));
        System.out.println("-------------------");
        System.out.println("Добавить Employee 11");
        System.out.println(employeeBook.addEmployee(new Employee("Name11", "Surname11", "SecondName11", 5, 16000)));
        System.out.println("-------------------");
        System.out.println("Удалить Employee 10");
        System.out.println(employeeBook.removeEmployeeById(10));
        System.out.println("-------------------");
        System.out.println("Получить Employee 10");
        System.out.println(employeeBook.getEmployeeById(10));
        System.out.println("-------------------");
        System.out.println("Получить Employee 1");
        System.out.println(employeeBook.getEmployeeById(1));
        System.out.println("-------------------");
        System.out.println("Получить список всех сотрудников со всеми имеющимися по ним данными");
        employeeBook.printAllEmployees();
        System.out.println("-------------------");
        System.out.println("Посчитать сумму затрат на ЗП в месяц");
        System.out.println(employeeBook.calculateMonthSalaryForAllEmployees());
        System.out.println("-------------------");
        System.out.println("Найти сотрудника с минимальной ЗП");
        System.out.println(employeeBook.findFirstEmployeeWithMinSalary());
        System.out.println("-------------------");
        System.out.println("Найти сотрудника с максимальной ЗП");
        System.out.println(employeeBook.findFirstEmployeeWithMaxSalary());
        System.out.println("-------------------");
        System.out.println("Подсчитать среднее значение зарплат");
        System.out.println(employeeBook.calculateMediumSalary());
        System.out.println("-------------------");
        System.out.println("Распечатать ФИО всех сотрудников");
        employeeBook.printAllEmployeesFio();
        System.out.println("-------------------");
        System.out.println("Проиндексировать зарплату на 10%");
        employeeBook.indexSalary(10.0);
        employeeBook.printAllEmployees();
        System.out.println("-------------------");
        System.out.println("Сотрудника с минимальной зп в департамерте 3");
        System.out.println(employeeBook.findFirstEmployeeWithMinSalaryByDepartment(3));
        System.out.println("-------------------");
        System.out.println("Сотрудника с максимальной зп в департамерте 1");
        System.out.println(employeeBook.findFirstEmployeeWithMaxSalaryByDepartment(1));
        System.out.println("-------------------");
        System.out.println("Сумму затрат на зп по отделу 5");
        System.out.println(employeeBook.calculateMonthSalaryForDepartment(5));
        System.out.println("-------------------");
        System.out.println("Среднюю зп по отделу 4");
        System.out.println(employeeBook.calculateMediumSalaryByDepartment(4));
        System.out.println("-------------------");
        System.out.println("Проиндексировать зарплату всех сотрудников отдела 2 на 10");
        employeeBook.indexSalaryByDepartment(10, 2);
        employeeBook.printAllEmployees();
        System.out.println("-------------------");
        System.out.println("Напечатать всех сотрудников отдела 1 (все данные, кроме отдела)");
        employeeBook.printEmployeesByDepartment(1);
        System.out.println("-------------------");
        System.out.println("Вывести: всех сотрудников с зп меньше 21000 (распечатать id, фио и зп в консоль)");
        employeeBook.printEmployeesWithLessSalary(21000);
        System.out.println("-------------------");
        System.out.println("Вывести: всех сотрудников с зп больше (или равно) 22000 (распечатать id, фио и зп в консоль)");
        employeeBook.printEmployeesWithMaxSalary(22000);
    }
}
